# Deployment pipeline definition
name: Deploy Angular to IIS

trigger:
  - main

pool:
  vmImage: 'windows-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '22.x'
    displayName: 'Install Node.js'

  - task: Npm@1
    inputs:
      command: 'install'
      workingDir: '$(System.DefaultWorkingDirectory)'
    displayName: 'NPM Install'

  - task: Npm@1
    inputs:
      command: 'custom'
      workingDir: '$(System.DefaultWorkingDirectory)'
      customCommand: 'run build'
    displayName: 'Build Angular App'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist/<CountryAppUI'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true
    displayName: 'Archive build output'

  - task: IISWebAppDeploymentOnMachineGroup@0
    inputs:
      webSiteName: 'Default Web Site'
      action: 'Create Or Update Website'
      physicalPath: 'C:\\inetpub\\wwwroot\\<CountryAppUI>'
      appPoolName: '<DefaultAppPool>'
      websiteBindings: 'http *:80:'
      iisWebAppDeploy: true
      package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    displayName: 'Deploy to IIS'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)/web.config'
      Contents: 'web.config'
      TargetFolder: 'C:\\inetpub\\wwwroot\\<CountryAppUI>'
    displayName: 'Copy web.config'